### ISSUE TITLE
KPFloating panel does not work

### ISSUE THREAD

**Issue by roquen** [mitchcapper/KPFloatingPanel#10]
Hi,
I have installed the KPFloatingPanel 7.5 plugin into my Keepass 2.3. I am running on Windows 10. The Keepass now give me the option to display the floating panel but nothing happens.
How can I fix this?

Thank you

**Comment by mitchcapper** [comment]
you don't see the floating panel (grey box with word keepass) anywhere on any of your monitors?

**Comment by roquen** [comment]
Dear Mitch,
thank you for coming back to me. No I do not see it anywhere. I have also
reviewed all open windows using alt+tab.

Kind regards,
Filip

2017-09-26 17:50 GMT+02:00 Mitch Capper <notifications@github.com>:

**Comment by roquen** [comment]
Dear Mitch,
I owe you an apology. I finally found the floating panel. It works
beautifully.

I would suggest some screenshots to add to the installing instructions on
how the panel looks like, because it is not what I expected and it does not
show among running applications if you use alt+tab, nor it is displayed in
task bar.

Kind regards,
Filip

2017-09-26 21:11 GMT+02:00 Filip Saska <saska.filip@gmail.com>:

**Comment by mitchcapper** [comment]
Happy you found it, was trying to figure a way to locate it but that makes sense.    The hiding from task bar/ alt tab is on purpose so that it doesn't take up those spaces.
