### ISSUE TITLE
search bar always hidden

### ISSUE THREAD

**Issue by franco27** [mitchcapper/KPFloatingPanel#13]
Hello

After installation, the extension worked correctly. After malfunction of the display:

1/I went down or went to select a password at the very bottom of the column.
2/ since , I can not see the search bar correctly
and go higher in the menu (or go up the search bar)
![image 2018-05-23 16 33 39 2018-05-23 16 34 23](https://user-images.githubusercontent.com/31793920/40431697-4132d69c-5ea8-11e8-8662-e8986adfc2b4.png)

3/ when I try to access the search bar, automatically scroll down.

**Comment by mitchcapper** [comment]
What do you mean by malfunction of display?
If you restart keepass is it fixed?
What versions are you using (of keepass and the plugin)?
What operating system are you running?

**Comment by franco27** [comment]
Thank you for your quick answer.

Windows 10 x64 - Keepass 2.39.1 et 7.5 plugin

I restarted Keepass and your plugin is working correctly again.
I repeated the steps to reproduce the problem and I could not repeat this problem.

**Comment by mitchcapper** [comment]
Will close if you can figure out how to reproduce may be able to look at further.  Have a nice day!
