### ISSUE TITLE
Incompatible plugin 

### ISSUE THREAD

**Issue by WorldSeso7** [mitchcapper/KPFloatingPanel#2]
sorry for my English
I installed the plugin but I get this error

![error](https://cloud.githubusercontent.com/assets/4233569/11622375/9a6a4b20-9cc5-11e5-82bf-835897e0481c.JPG)

Keep Pass version is the latest available (2.30)
S.o. Win 10 
moreover also deleting the plugin from folder of the program can not remove the error

I uninstalled and deleted the Keepass folder 

After installing again now I have 2 times the error

**Comment by mitchcapper** [comment]
I downloaded KeePass portable ("KeePass-2.30.zip") and extracted to: c:\temp\kp  I then downloaded:
https://github.com/mitchcapper/KPFloatingPanel/releases/download/7.0/KPFloatingPanel.plgx
and saved it to: c:\temp\kp\KPFloatingPanel.plgx
then launched keepass.exe and it works for me (after compiling) but you are getting the above error?  Can you try the above steps and see if it also happens the same?

**Comment by WorldSeso7** [comment]
I uninstalled keepass and also deleted folders under user/appdata/local/.... and roaming but also with portable keepass the result is the same

**Comment by Glock3am** [comment]
Hi, I have the same error. I'm running the installed version of KeePass 2 2.30 on Win 7 x64 with KPFloatingPanel 7.0.

I have also deleted the .dll file folder under Users\Username\AppData\Local\KeePass\PluginCache\ and started fresh and get the same error.

Deleting both the .plgx and aforementioned folder allows normal operation again.

Even stranger is that removing all and going back to an earlier version of the floating panel (6.1) results in the same error! Is there anywhere else that customised display settings are stored? After installing the new version I did do a little extra tweaking to colours and transparency that may have caused an issue perhaps.

I think this because in my attached screenshot below of the error message, it appears to be a problem with how KeePass/KPFloatingPanel handles the transparency of the panel?

![error](https://cloud.githubusercontent.com/assets/16218795/11677577/cad67574-9e71-11e5-82bd-f497bf5592da.png)

**Comment by mitchcapper** [comment]
This is very odd.  I am going to try and install a new Windows 10 virtual machine, as I have tried on several but been unable to replicate.   Can you run keepass with --debug  and see if that gives a more useful error message?

**Comment by Glock3am** [comment]
OK, I've run it with the debug switch and I only get the same information as before (attached image).

By the way I am also running a couple of other plugins, Favicons Downloader (1.6.0.0) and KeePassHttp (1.8.4.0) if that helps.

Also, I just tried with a clean portable installation, with no other plugins and got the same result.

![error debug](https://cloud.githubusercontent.com/assets/16218795/11677902/998ae37a-9e75-11e5-9569-567cc4ce39aa.png)

**Comment by mswietlik** [comment]
Same error with clean KeePass 2.30.

**Comment by mitchcapper** [comment]
That is odd.  I tried changing the the transparency and colors and couldn't get it to happen.  The registry settings are stored in: HKEY_CURRENT_USER\Software\KeePassFloatingPanel  you can delete that folder and see if that solves it.  I will try to get a Windows VM spun up soon to replicate this on a clean machine.

**Comment by mitchcapper** [comment]
Sorry for the delay, setup a Win7.1 virtual machine.  Downloaded the PLGX and keepass portable and ran it.  I received a different error (related to a resource file).  I installed the latest windows updates which included .net 4.6 and restarted and it worked fine.   Can you try the .net 4.6 installer to make sure you have the latest version of .net? https://www.microsoft.com/en-us/download/details.aspx?id=48130  if that solves it I can see about making it work with other versions.

**Comment by Glock3am** [comment]
No problem. I was on .NET 4.5.2. I tried .NET 4.6 and .NET 4.6.1 and the error persists.

**Comment by mitchcapper** [comment]
This is very puzzling.   I installed Win 7 SP1,  installed the .net 4.6, and used the portable keepass with the plugin without an issue.     I have done some research on the error and the plgx attached _may_ fix it.   I know you guys have already tried the portable version so it probably is not another plugin.   Do you have any theme changes or anything like that?  As its happening on Win 7 and Win 10 its further interesting.  Let me know if this works.
[KPFloatingPanel.zip](https://github.com/mitchcapper/KPFloatingPanel/files/81552/KPFloatingPanel.zip)

**Comment by RomeuLopes** [comment]
Sorry about my English. I'm from Brazil.

Here gave the same error above.

I deleted HKEY_CURRENT_USER \ Software \ KeePassFloatingPanel and resolved.

I use Win7. KP 2.3.1 Portable

**Comment by Glock3am** [comment]
Oh wow, this totally worked!

I didn't even think of checking the registry for old configs. Well done RomeuLopes!

**Comment by mitchcapper** [comment]
Anyone who was having this issue try the plugin update I posted to see if that fixed it?

**Comment by mswietlik** [comment]
Yes, for me it did.

**Comment by mitchcapper** [comment]
alright I put the fix in the main branch.
