### ISSUE TITLE
Hotkeys do not work

### ISSUE THREAD

**Issue by CollinChaffin** [mitchcapper/KPFloatingPanel#8]
Have the hotkeys defined in this plugin settings ever worked properly?  I also cannot seem to get any hotkey to function defined in this plugin settings.  They do remain set even upon a close/reopen, just never actually seem to activate regardless of whether I have the desktop active, or an application.

**Comment by mitchcapper** [comment]
What platform are you running, have you tried the default hot keys? Even with changing they do seem to operate fine for me.

**Comment by CollinChaffin** [comment]
Windows 7 x64.  Setting both hotkey options both global and quickpwd to different combinations cannot get either to activate at all.

**Comment by mitchcapper** [comment]
I can't imagine what would stop them from working, did the defaults work or no?  Also make sure you don't have another copy of keepass running at startup as that could prevent binding.

**Comment by mitchcapper** [comment]
Closing this due to non response.
